# =====================================================================
# INGRESS – Local Nginx Ingress Controller
# Mapping api.local and frontend.local (or using sslip.io)
# =====================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: microservices
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.local
        - 192.168.88.50
      secretName: microservices-tls
  rules:
    - host: api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 9000
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-react
                port:
                  number: 80
