# =====================================================================
# PERSISTENT VOLUME CLAIMS
# premium-rwo = SSD persistent disk sur GKE (ReadWriteOnce)
# =====================================================================

# MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: microservices
  labels:
    app: mongodb
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# PostgreSQL Groupe
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-groupe-pvc
  namespace: microservices
  labels:
    app: postgres-groupe
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# PostgreSQL Travail
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-travail-pvc
  namespace: microservices
  labels:
    app: postgres-travail
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Uploads images étudiants (Direct Local Path - Single Node Fix)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etudiant-images-pvc
  namespace: microservices
  labels:
    app: etudiant-service
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
