spring.application.name=etudiant-service
server.port=8080
spring.data.mongodb.uri=mongodb://adrien:franto@mongodb-service:27017/etudiant-service?authSource=admin&authMechanism=SCRAM-SHA-256&connectTimeoutMS=10000

# Logging & Actuator
logging.level.org.springframework.data.mongodb=DEBUG
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
